=== jonastogo/SkriptHausaufgaben/SkriptHausaufgaben/Skript09/kundenliste.dtd
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE kundenliste
[
<!ELEMENT kundenliste(VIP*,Standart*)>
<!ELEMENT VIP (Kunde*)>
<!ELEMENT Kunde(name,Straße,Hausnummer,PLZ,Ort,Ansprechpartnerliste*,Betreuer+,Bemerkung)>
<!ELEMENT name(#PCDATA)>
<!ATTLIST name kategorie CDATA #REQUIRED > 
<!ELEMENT Straße(#PCDATA)>
<!ELEMENT Hausnummer(#PCDATA)>
<!ELEMENT PLZ(#PCDATA)>
<!ELEMENT Ort(#PCDATA)>
<!ELEMENT Ansprechpartnerliste (Ansprechpartner*)>
<!ELEMENT Anprechpartner (name,vorname,position,Telefonnummer)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT Telefonnummer (#PCDATA)>
<!ELEMENT Betreuer(name,vorname)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT Bemerkung(#PCDATA)>
<!ATTLIST Bemerkung kategorie CDATA #REQUIRED > 	

<!ELEMENT Standart (Kunde*)>
<!ELEMENT Kunde(name,Straße,Hausnummer,PLZ,Ort,Ansprechpartnerliste*,Betreuer+,Bemerkung)>
<!ELEMENT name(#PCDATA)>
<!ATTLIST name kategorie CDATA #REQUIRED > 
<!ELEMENT Straße(#PCDATA)>
<!ELEMENT Hausnummer(#PCDATA)>
<!ELEMENT PLZ(#PCDATA)>
<!ELEMENT Ort(#PCDATA)>
<!ELEMENT Ansprechpartnerliste (Ansprechpartner*)>
<!ELEMENT Anprechpartner (name,vorname,position,Telefonnummer)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT Telefonnummer (#PCDATA)>
<!ELEMENT Betreuer(name,vorname)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT Bemerkung(#PCDATA)>
<!ATTLIST Bemerkung kategorie CDATA #REQUIRED > 	

]>

=== jonastogo/SkriptHausaufgaben/SkriptHausaufgaben/Skript09/Kundenliste.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bild SYSTEM "kundenliste.dtd">
<kundenliste>
		<Kunde>
			<name>Baxter</name>
			<Straße>Kantstraße</Straße>
			<Hausnummer>2</Hausnummer>
			<PLZ>33790</PLZ>
			<Ort>Halle</Ort>
			<Ansprechpartnerliste anzahl="1">
				<Ansprechpartner>
					<name>Muster</name>
					<vorname>Peter</vorname>
					<position>Abteilungsleiter Entwicklung</position>
					<Telefonnummer>01645863138546</Telefonnummer>	
				</Ansprechpartner>			
			</Ansprechpartnerliste>
			<Betreuer>
				<name>Peters</name>
				<vorname>Hans</vorname>
			</Betreuer>
			<Bemerkung></Bemerkung>
		</Kunde>
		<Kunde>
			<name>Baxter</name>
			<Straße>Kantstraße</Straße>
			<Hausnummer>2</Hausnummer>
			<PLZ>33790</PLZ>
			<Ort>Halle</Ort>
			<Ansprechpartnerliste anzahl="1">
				<Ansprechpartner>
					<name>Muster</name>
					<vorname>Peter</vorname>
					<position>Abteilungsleiter Entwicklung</position>
					<Telefonnummer>01645863138546</Telefonnummer>	
				</Ansprechpartner>			
			</Ansprechpartnerliste>
			<Betreuer>
				<name>Peters</name>
				<vorname>Hans</vorname>
			</Betreuer>
			<Bemerkung></Bemerkung>
		</Kunde>	
</kundenliste>
